### ISSUE TITLE
Greek language

### ISSUE THREAD

**Issue by MalakasPlayzMC** [CLADevs/CLACore#10]
>---
>
>language.name: Ελληνικά
>
>#General
>no.permission: §cΔεν έχεις τα δικαιώματα να το κάνεις αυτό.
>player.not.found: §cΑυτός ο παίκτης δεν μπορεί να βρεθεί.
>
>#FeedCommand, HealCommand, VanishCommand & FlyCommand
>player.fed: §aΈχεις ταϊστεί.
>sender.fed: §bΟ/Η {player} §aέχει ταϊστεί.
>
>player.healed: §aΈχεις αναζωογονηθεί.
>sender.healed: §bΟ/Η {player} §aέχει αναζωογονηθεί.
>
>player.vanished: §aΈχεις εξαφανιστεί.
>sender.vanished: §bΟ/Η {player} §aέχει εξαφανιστεί.
>
>flightmode.on: §aΤώρα μπορείς να πετάξεις.
>flightmode.off: §cΔεν μπορείς να πετάξεις άλλο.
>
>#StaffChatCommand
>staffchat.enabled: §bΤο §eStaffChat §aΕνεργοποιήθηκε.
>staffchat.disabled: §bΤο §eStaffChat §cΑπενεργοποιήθηκε.
>...

**Comment by xXNiceAssasinl0** [comment]
U have discord

**Comment by xXNiceAssasinl0** [comment]
Try pull requesting

**Comment by MalakasPlayzMC** [comment]
Yes, I have discord: MalakasPlayzMC#3797

**Comment by PotatoeTrainYT** [comment]
https://github.com/CLADevs/CLACore/commit/07b5279c9e0fbc79d57b50711c084fde4420afac
