### ISSUE TITLE
Device Blocker

### ISSUE THREAD

**Issue by armagadon159753** [CLADevs/CLACore#16]
Use config to block device when player Join:

Exemple: W10, IOS, Android ect....

**Comment by ErkamKahriman** [comment]
I will implement this function to CLACore

**Comment by armagadon159753** [comment]
@ErkamKahriman if you want -_- then look #5 Forst plz

**Comment by xXNiceAssasinl0** [comment]
@ErkamKahriman you have been invited to group.

**Comment by ErkamKahriman** [comment]
@armagadon159753 i mean Device blocking

**Comment by ErkamKahriman** [comment]
Not nametag above player

**Comment by xXNiceAssasinl0** [comment]
@ErkamKahriman accept join CLADevs ;)

**Comment by ErkamKahriman** [comment]
Already accepted lol

**Comment by armagadon159753** [comment]
Ahah @ErkamKahriman no 😂 i mean check m'y pr  about how to get the device of the  player

**Comment by xXNiceAssasinl0** [comment]
K

**Comment by armagadon159753** [comment]
@xXNiceAssasinl0 @ErkamKahriman I will make my owne device blocker I will need W10 player and IOS

**Comment by armagadon159753** [comment]
#39
