### ISSUE TITLE
Why cant yiu add this????

### ISSUE THREAD

**Issue by BurritoMan46** [CLADevs/CLACore#2]
Add McMMO if u don't know then your not a dev..

**Comment by xXNiceAssasinl0** [comment]
Fine we’ll add xd

**Comment by KirbyKYS** [comment]
This isn't an issue BurritoMan46... Make a pull request yourself 🗡

**Comment by BurritoMan46** [comment]
@KirbyKYS fuck off my nigger

**Comment by BigDGucciPvP** [comment]
@BurritoMan46 okay toxic

**Comment by BurritoMan46** [comment]
Lmao
