### ISSUE TITLE
;P

### ISSUE THREAD

**Issue by DJTMGaming** [CLADevs/CLACore#29]
Enabling CLACore v1.0.0
16.01 02:53:42 [Server] Server thread/CRITICAL Error: "Class 'Events\onMoveEvent' not found" (EXCEPTION) in "CLACore_dev-58.phar/src/CLACore/Core" at line 70
16.01 02:53:42 [Server] Server thread/DEBUG #0 CLACore_dev-58.phar/src/CLACore/Core(41): CLACore\Core->onEvent()
16.01 02:53:42 [Server] Server thread/DEBUG #1 src/pocketmine/plugin/PluginBase(90): CLACore\Core->onEnable()
16.01 02:53:42 [Server] Server thread/DEBUG #2 src/pocketmine/plugin/PharPluginLoader(122): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
16.01 02:53:42 [Server] Server thread/DEBUG #3 src/pocketmine/plugin/PluginManager(610): pocketmine\plugin\PharPluginLoader->enablePlugin(CLACore\Core object)
16.01 02:53:42 [Server] Server thread/DEBUG #4 src/pocketmine/Server(1957): pocketmine\plugin\PluginManager->enablePlugin(CLACore\Core object)
16.01 02:53:42 [Server] Server thread/DEBUG #5 src/pocketmine/Server(1943): pocketmine\Server->enablePlugin(CLACore\Core object)
16.01 02:53:42 [Server] Server thread/DEBUG #6 src/pocketmine/Server(1737): pocketmine\Server->enablePlugins(integer 1)
16.01 02:53:42 [Server] Server thread/DEBUG #7 src/pocketmine/PocketMine(554): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
16.01 02:53:42 [Server] Server thread/DEBUG #8 /pmmp585.phar(1): require(string phar:///pmmp585.phar/src/pocketmine/PocketMine.php)
16.01 02:53:42 [Server] Server thread/INFO Disabling CLACore v1.0.0
16.01 02:53:42 [Server] Server thread/INFO Disabled.
16.01 02:53:42 [Server] Server thread/INFO Enabling CLAJoin vv0.0.1
16.01 02:53:42 [Server] Server thread/CRITICAL Error: "Class 'CLADevs\CLLADevs' not found" (EXCEPTION) in "CLAJoin_dev-14.phar/src/CLADevs/Main" at line 17
16.01 02:53:42 [Server] Server thread/DEBUG #0 src/pocketmine/plugin/PluginBase(90): CLADevs\Main->onEnable()
16.01 02:53:42 [Server] Server thread/DEBUG #1 src/pocketmine/plugin/PharPluginLoader(122): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
16.01 02:53:42 [Server] Server thread/DEBUG #2 src/pocketmine/plugin/PluginManager(610): pocketmine\plugin\PharPluginLoader->enablePlugin(CLADevs\Main object)
16.01 02:53:42 [Server] Server thread/DEBUG #3 src/pocketmine/Server(1957): pocketmine\plugin\PluginManager->enablePlugin(CLADevs\Main object)
16.01 02:53:42 [Server] Server thread/DEBUG #4 src/pocketmine/Server(1943): pocketmine\Server->enablePlugin(CLADevs\Main object)
16.01 02:53:42 [Server] Server thread/DEBUG #5 src/pocketmine/Server(1737): pocketmine\Server->enablePlugins(integer 1)
16.01 02:53:42 [Server] Server thread/DEBUG #6 src/pocketmine/PocketMine(554): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
16.01 02:53:42 [Server] Server thread/DEBUG #7 /pmmp585.phar(1): require(string phar:///pmmp585.phar/src/pocketmine/PocketMine.php)
16.01 02:53:42 [Server] Server thread/INFO Disabling CLAJoin vv0.0.1

**Comment by DJTMGaming** [comment]
<strong> might be helpful </strong>

**Comment by SuperKali** [comment]
@DJTMGaming try last commit

**Comment by DJTMGaming** [comment]
ok

**Comment by DJTMGaming** [comment]
Enabling CLAJoin vv0.0.1
16.01 05:03:25 [Server] Server thread/CRITICAL Error: "Class 'CLADevs\CLLADevs' not found" (EXCEPTION) in "CLAJoin_dev-14.phar/src/CLADevs/Main" at line 17
16.01 05:03:25 [Server] Server thread/DEBUG #0 src/pocketmine/plugin/PluginBase(90): CLADevs\Main->onEnable()
16.01 05:03:25 [Server] Server thread/DEBUG #1 src/pocketmine/plugin/PharPluginLoader(122): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
16.01 05:03:25 [Server] Server thread/DEBUG #2 src/pocketmine/plugin/PluginManager(610): pocketmine\plugin\PharPluginLoader->enablePlugin(CLADevs\Main object)
16.01 05:03:25 [Server] Server thread/DEBUG #3 src/pocketmine/Server(1957): pocketmine\plugin\PluginManager->enablePlugin(CLADevs\Main object)
16.01 05:03:25 [Server] Server thread/DEBUG #4 src/pocketmine/Server(1943): pocketmine\Server->enablePlugin(CLADevs\Main object)
16.01 05:03:25 [Server] Server thread/DEBUG #5 src/pocketmine/Server(1737): pocketmine\Server->enablePlugins(integer 1)
16.01 05:03:25 [Server] Server thread/DEBUG #6 src/pocketmine/PocketMine(554): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
16.01 05:03:25 [Server] Server thread/DEBUG #7 /pmmp585.phar(1): require(string phar:///pmmp585.phar/src/pocketmine/PocketMine.php)
16.01 05:03:25 [Server] Server thread/INFO Disabling CLAJoin vv0.0.1
