### ISSUE TITLE
Can you add staffchat

### ISSUE THREAD

**Issue by goodmario1** [CLADevs/CLACore#3]
Hello, I was wondering if you can add staffchat. I would much appreciate it!

**Comment by xXNiceAssasinl0** [comment]
Any example don’t really know what u mean by staff chat

**Comment by ErkamKahriman** [comment]
I think he mean TeamChat. Players with permissions or op can chat together with /tc oder anythink like that.

**Comment by goodmario1** [comment]
Yes, what ErkamKahriman said kind of like a team chat but for staff

**Comment by ErkamKahriman** [comment]
@xXNiceAssasinl0 should i add it?

**Comment by xXNiceAssasinl0** [comment]
@ErkamKahriman sure if you can
