### ISSUE TITLE
Useless code and reformat syntax !

### ISSUE THREAD

**Issue by armagadon159753** [CLADevs/CLACore#33]
https://github.com/CLADevs/CLACore/tree/master/src/CLACore/Commands
https://github.com/CLADevs/CLACore/tree/master/src/Commands

**Comment by xXNiceAssasinl0** [comment]
Fixed

**Comment by armagadon159753** [comment]
Useless folders has been removed but we need remake code for better looking

**Comment by xXNiceAssasinl0** [comment]
-_- you do it yourself

**Comment by armagadon159753** [comment]
K this is why I was assigned myself

**Comment by xXNiceAssasinl0** [comment]
Who going help you than lol I am doing my work

**Comment by armagadon159753** [comment]
#35
