### ISSUE TITLE
Balance Command

### ISSUE THREAD

**Issue by ghost** [CLADevs/CLACore#34]
Hello CLADevs, I have a idea that you could add a balance command for the economy part of your Core.
For Example; I did /bal, /balance, /mymoney it would show the amount of money you or a player has. I think this would be really good. To me it kind of balances the economy. Ehh get my little pun. But seriously, to me it does balance the economy.

Thanks for reading this and hopefully you add this.

Regards> - HysteriaMCPE

**Comment by xXNiceAssasinl0** [comment]
Okay

**Comment by HysteriaMCPE** [comment]
Awesome, what do you mean by "okay"???

**Comment by xXNiceAssasinl0** [comment]
We will added soon enough, I am super busy on my server.

**Comment by HysteriaMCPE** [comment]
Okay. You have a good time making plugins and running servers. C ya

**Comment by xXNiceAssasinl0** [comment]
Thanks!
