### ISSUE TITLE
TPA System

### ISSUE THREAD

**Issue by ghost** [CLADevs/CLACore#36]
Hello CLA Devs, I have a request. It's TPA, TPAHere, TPAAccept, TPADeny, TPO, TPAll. I will tell you what they do.

#1) TPA: What TPA is basically asking another player for themselve to tp to player.
#2) TPAccept: TPAAccept is when the player excepts a tp.
#3) TPDeny: TPADeny is when the player denied a tp.
#4) TPO: Automatic tp to player.
#5) TPAll: TP's all player's to yourself

**Comment by armagadon159753** [comment]
Good idea

**Comment by FreakkDev** [comment]
thx

**Comment by armagadon159753** [comment]
#39
