### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by FreakkDev** [CLADevs/CLACore#38]
Hello CLADevs, may i have permission to use the economy part of your plugin for my essentials core?

**Comment by PotatoeTrainYT** [comment]
you have permission, its not fully ours its our version of EconomyAPI

**Comment by FreakkDev** [comment]
thx

**Comment by armagadon159753** [comment]
Dont forgot to credit CLADev team

**Comment by xXNiceAssasinl0** [comment]
please ask @SuperKali it’s his Economy lol.
