### ISSUE TITLE
Add this

### ISSUE THREAD

**Issue by Kaneki-chi** [CLADevs/CLACore#4]
When a player of iOS joins the game his nametag is [iOS] {playername}
When a player of WIN10 joins the game his nametag is [Win10] {playername}
When a player of Android oins the game his nametag is [Android] {playername}

**Comment by xXNiceAssasinl0** [comment]
It’s not possible

**Comment by Kaneki-chi** [comment]
<?php

namespace DeviceInfo;

use pocketmine\event\Listener;
use pocketmine\plugin\PluginBase;
use pocketmine\event\player\PlayerJoinEvent;
use pocketmine\event\server\DataPacketReceiveEvent;

class Main extends PluginBase implements Listener{ 

public function onEnable(){
$this->getServer()->getPluginManager()->registerEvents($this, $this);
$this->getLogger()->info("DeviceInfo has been enable");
}

public function onJoin(PlayerJoinEvent $event){
$event->getPlayer()->setNameTag("§6".$this->data[$event->getPlayer()->getName()]["OS"]." §b".$event->getPlayer()->getName());
}

public function getDevice(DataPacketReceiveEvent $event){
if($event->getPacket() instanceof LoginPacket){
$device = $event->getPacket()->clientData["DeviceOS"];
$types = ["Unknown", "Android", "iOS", "macOS", "FireOS", "GearVR", "HoloLens", "Windows10", "Windows", "Dedicated", "Orbis", "NX"];
$this->data[$event->getPacket()->username] = ["OS" => $types[$device]];}}}

**Comment by xXNiceAssasinl0** [comment]
I cannot understand? It’s junks

**Comment by Kaneki-chi** [comment]
<?php

namespace DeviceInfo;

use pocketmine\event\Listener;
use pocketmine\plugin\PluginBase;
use pocketmine\event\player\PlayerJoinEvent;
use pocketmine\event\server\DataPacketReceiveEvent;

class Main extends PluginBase implements Listener{ 

public function onEnable(){
$this->getServer()->getPluginManager()->registerEvents($this, $this);
$this->getLogger()->info("DeviceInfo has been enable");
}

public function onJoin(PlayerJoinEvent $event){
$event->getPlayer()->setNameTag("§6".$this->data[$event->getPlayer()->getName()]["OS"]." §b".$event->getPlayer()->getName());
}

public function getDevice(DataPacketReceiveEvent $event){
if($event->getPacket() instanceof LoginPacket){
$device = $event->getPacket()->clientData["DeviceOS"];
$types = ["Unknown", "Android", "iOS", "macOS", "FireOS", "GearVR", "HoloLens", "Windows10", "Windows", "Dedicated", "Orbis", "NX"];
$this->data[$event->getPacket()->username] = ["OS" => $types[$device]];}}}

**Comment by armagadon159753** [comment]
GetPlayerDevice
GetDeviceOS

Maybe if i have the time i will do an pr

**Comment by xXNiceAssasinl0** [comment]
Armagadon what ur discord?

**Comment by armagadon159753** [comment]
ArmTheDev#9575

**Comment by Kaneki-chi** [comment]
As I can send you an example of code?

**Comment by xXNiceAssasinl0** [comment]
@Kaneki-chi you have discord

**Comment by Kaneki-chi** [comment]
Yes

**Comment by xXNiceAssasinl0** [comment]
Join our discord

**Comment by xXNiceAssasinl0** [comment]
https://discord.gg/V5CYfWd
