### ISSUE TITLE
Kill Message

### ISSUE THREAD

**Issue by ghost** [CLADevs/CLACore#40]
Hello CLADevs, I have a request. Basically when a player had kill someone, it would say <player> has been killed by <player[1]>. The [1] is how many kills a player has. Everytime a certain player kills some1 it would say, <player> has been Killed by <player[kills]>.

Regards: FreakkDev

**Comment by PotatoeTrainYT** [comment]
this is a good idea however some people may not like it so i will add something like {VICTIM} {KILLER} {KILLER-KILLS} {VICTIM-DEATHS}

**Comment by FreakkDev** [comment]
thats fine

**Comment by armagadon159753** [comment]
#39
