### ISSUE TITLE
High Ping Kick

### ISSUE THREAD

**Issue by CupidonSauce173** [CLADevs/CLACore#45]
I do not know if this is your plugin but when I put it on, it start to kick players with high ping and when I remove it, it stop. 

I love your plugin, for real, it's so nice. But I needed to remove it. There is a possibility to change the max ping that a player can have before he/she get kick ? 

How to reproduce this issue
-put the plugin on the plugins files.
-open the server.

**Comment by xXNiceAssasinl0** [comment]
I’ll try fix, tomorrow in tired Coding thank for reporting have a nice day @CupidonSauce173!

**Comment by PotatoeTrainYT** [comment]
yeah. this is our plugin we will add a fix to this in the morning. thanks for telling us this

**Comment by PotatoeTrainYT** [comment]
should be fixed. someone must of removed it from config so i added back.

**Comment by xXNiceAssasinl0** [comment]
Ya it maybe me xD

**Comment by CupidonSauce173** [comment]
Everything else work really fine. Maybe you could just add a option in the Config.yml to put the max ping that a player can have because for real, this could be a good feature ;)

**Comment by xXNiceAssasinl0** [comment]
Already added

**Comment by ShatteredAtom** [comment]
how bout add an option to disable

**Comment by xXNiceAssasinl0** [comment]
It’s in config :/

**Comment by CupidonSauce173** [comment]
Yes I saw it

**Comment by xXNiceAssasinl0** [comment]
Englush?
