### ISSUE TITLE
add commands

### ISSUE THREAD

**Issue by Kaneki-chi** [CLADevs/CLACore#7]
command: hub
command: lobby
command: spawn
command: kill

**Comment by xXNiceAssasinl0** [comment]
Can u calm down with this idea but I will not do /setrank

**Comment by Kaneki-chi** [comment]
it's okay xD

**Comment by ByWeeD** [comment]
L

**Comment by XDqrkneZ** [comment]
What are the difference between hub, lobby and spawn? Isn't /kill a default minecraft command? What's the point of adding it?

**Comment by xXNiceAssasinl0** [comment]
@XDqrkneZ He mean /kill @e, etc

**Comment by xXNiceAssasinl0** [comment]
It kill everything
