### ISSUE TITLE
Combat Title and message

### ISSUE THREAD

**Issue by ghost** [CLADevs/CLACore#8]
Hello xXNice, I was wondering if you could add Combat Title. What I mean is when you get hit, It shows a title that says (name of attacker) combat Tagged You(Configurable). Also add a message that says for how long you will be tagged before you can logout. When your Combat timer runs out it will send a message or title. That says your not in combat, You may safely log out.

Regards -InfernoPE

**Comment by xXNiceAssasinl0** [comment]
Sure tomrrow I have to sleep right now.

**Comment by InfernoPE** [comment]
You get your sleep. Your a good man

**Comment by xXNiceAssasinl0** [comment]
Thanks man.

**Comment by armagadon159753** [comment]
#39
